[colors.primary]
  background = "#1a1b26"
  foreground = "#a9b1d6"

[colors.normal]
  black = "#32344a"
  red = "#f7768e"
  green = "#9ece6a"
  yellow = "#e0af68"
  blue = "#7aa2f7"
  magenta = "#ad8ee6"
  cyan = "#449dab"
  white = "#787c99"

[colors.bright]
  black = "#444b6a"
  red = "#ff7a93"
  green = "#b9f27c"
  yellow = "#ff9e64"
  blue = "#7da6ff"
  magenta = "#bb9af7"

[env]
  TERM = "xterm-256color"

[font]
  size = 16.0

[font.bold]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"

[font.italic]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"

[font.normal]
  family = "JetBrainsMono Nerd Font Mono"
  style = "Regular"

[font.glyph_offset]
  x = 0
  y = 0

[font.offset]
  x = 0
  y = 0

[window]
  startup_mode = "Fullscreen"
  opacity = 0.90

[window.dimensions]
  columns = 110
  lines = 33

[window.padding]
  x = 0
  y = 0
